spring.datasource.url=jdbc:postgresql://postgres:5432/thirdgear_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=noreply@thirdgear.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
jwt.secret=thirdgear_secret_key_for_jwt_token_signing_must_be_long
jwt.expiration=86400000